import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import HeaderWrapper from "@/components/HeaderWrapper";
import SidebarWrapper from "@/components/SidebarWrapper";
import ToasterProvider from "@/components/providers/ToasterProvider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import  AppSidebar  from "@/components/AppSidebar";
import AppHeader from "@/components/AppHeader";
import ClientLayout from "@/components/ClientLayout";


export const metadata: Metadata = {
  title: "HRMS",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
//  const hideHeaderRoutes = ["/login"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
      <body>
        <Providers>
          {/* CLIENT LOGIC MOVED HERE */}
          <ClientLayout>{children}</ClientLayout>
        </Providers>
      </body>
    </html>
  );
}
