import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import ClientLayout from "@/components/ClientLayout";


export const metadata: Metadata = {
  title: "HRMS",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
//  const hideHeaderRoutes = ["/login"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ClientLayout>{children}</ClientLayout>
          <ClientLayout>
            {/* COMMON ALIGNMENT WRAPPER */}
            <div className="px-0 py-0">
              {children}
            </div>
          </ClientLayout>
        </Providers>
      </body>
    </html>
  );
}

